[package]
name = "FinancerSTD"
version = "0.1.0"
upgrade_policy = "compatible"
license = "Apache-2.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }

[addresses]
financer_std="0x8f3fd4fa708e5b3bff4019b801d2d3d0ae16cf430440fff32ede61c09e001ec6"
